# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\x04test\"!\n\x12Statistics_request\x12\x0b\n\x03req\x18\x01 \x01(\t\"\"\n\x13Statistics_response\x12\x0b\n\x03log\x18\x01 \x01(\x0c\x32L\n\nStatistics\x12>\n\x07get_log\x12\x18.test.Statistics_request\x1a\x19.test.Statistics_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATISTICS_REQUEST']._serialized_start=26
  _globals['_STATISTICS_REQUEST']._serialized_end=59
  _globals['_STATISTICS_RESPONSE']._serialized_start=61
  _globals['_STATISTICS_RESPONSE']._serialized_end=95
  _globals['_STATISTICS']._serialized_start=97
  _globals['_STATISTICS']._serialized_end=173
# @@protoc_insertion_point(module_scope)
