# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import statistics_pb2 as statistics__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatisticsStub(object):
    """定义Statistics服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_log = channel.unary_unary(
                '/test.Statistics/get_log',
                request_serializer=statistics__pb2.Statistics_request.SerializeToString,
                response_deserializer=statistics__pb2.Statistics_response.FromString,
                _registered_method=True)


class StatisticsServicer(object):
    """定义Statistics服务
    """

    def get_log(self, request, context):
        """定义get_log方法，接收Statistics_request，返回Statistics_response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_log': grpc.unary_unary_rpc_method_handler(
                    servicer.get_log,
                    request_deserializer=statistics__pb2.Statistics_request.FromString,
                    response_serializer=statistics__pb2.Statistics_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Statistics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('test.Statistics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Statistics(object):
    """定义Statistics服务
    """

    @staticmethod
    def get_log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/test.Statistics/get_log',
            statistics__pb2.Statistics_request.SerializeToString,
            statistics__pb2.Statistics_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
